<a href="https://colab.research.google.com/github/pavi116tra/CodSoft/blob/main/Churn_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df = df[[
    "CreditScore",
    "Geography",
    "Gender",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
    "EstimatedSalary",
    "Exited"          # Target
]]


In [4]:
encoder = OrdinalEncoder(

)

df[["Geography", "Gender"]] = encoder.fit_transform(
    df[["Geography", "Gender"]]
)


In [5]:
X = df.drop("Exited", axis=1)
y = df["Exited"]


In [6]:
X = X.fillna(X.median())


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42, stratify=y)


In [8]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train, y_train)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(class_weight='balanced', max_iter=1000)

In [9]:
y_pred = model.predict(X_test)


In [10]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.6875

Confusion Matrix:
 [[1087  506]
 [ 119  288]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.68      0.78      1593
           1       0.36      0.71      0.48       407

    accuracy                           0.69      2000
   macro avg       0.63      0.69      0.63      2000
weighted avg       0.79      0.69      0.72      2000



In [11]:
from sklearn.ensemble import RandomForestClassifier


In [12]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,)

rf_model.fit(X_train, y_train)


RandomForestClassifier(max_depth=8)

In [13]:
y_pred_rf = rf_model.predict(X_test)


In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification RePort:\n", classification_report(y_test, y_pred_rf))


Random Forest Accuracy: 0.8645

Confusion Matrix:
 [[1558   35]
 [ 236  171]]

Classification RePort:
               precision    recall  f1-score   support

           0       0.87      0.98      0.92      1593
           1       0.83      0.42      0.56       407

    accuracy                           0.86      2000
   macro avg       0.85      0.70      0.74      2000
weighted avg       0.86      0.86      0.85      2000



In [15]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    class_weight="balanced",
    max_iter=5000
)

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("Linear SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))


Linear SVM Accuracy: 0.656
[[1034  559]
 [ 129  278]]
              precision    recall  f1-score   support

           0       0.89      0.65      0.75      1593
           1       0.33      0.68      0.45       407

    accuracy                           0.66      2000
   macro avg       0.61      0.67      0.60      2000
weighted avg       0.78      0.66      0.69      2000



In [16]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7465
[[1231  362]
 [ 145  262]]
              precision    recall  f1-score   support

           0       0.89      0.77      0.83      1593
           1       0.42      0.64      0.51       407

    accuracy                           0.75      2000
   macro avg       0.66      0.71      0.67      2000
weighted avg       0.80      0.75      0.76      2000



In [17]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nb_model = GaussianNB()

nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

Naive Bayes Accuracy: 0.7855
[[1545   48]
 [ 381   26]]
              precision    recall  f1-score   support

           0       0.80      0.97      0.88      1593
           1       0.35      0.06      0.11       407

    accuracy                           0.79      2000
   macro avg       0.58      0.52      0.49      2000
weighted avg       0.71      0.79      0.72      2000



In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.5495

Confusion Matrix:
 [[886 707]
 [194 213]]

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.56      0.66      1593
           1       0.23      0.52      0.32       407

    accuracy                           0.55      2000
   macro avg       0.53      0.54      0.49      2000
weighted avg       0.70      0.55      0.59      2000



In [19]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7465
[[1231  362]
 [ 145  262]]
              precision    recall  f1-score   support

           0       0.89      0.77      0.83      1593
           1       0.42      0.64      0.51       407

    accuracy                           0.75      2000
   macro avg       0.66      0.71      0.67      2000
weighted avg       0.80      0.75      0.76      2000



In [20]:
import joblib

joblib.dump(model, "churnmodel.pkl")
from google.colab import files
files.download("churnmodel.pkl")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
%%writefile main.py
# put your full ML code here
print("ML Project")

Writing main.py


In [ ]:
files.download("main.py")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>